name: ClothCommand
main: com.imjake9.clothcommand.ClothCommand
version: 1.3.1
commands:
    cloth:
        description: Gives players cloth
        usage: |
               /<command> <color> [amount] [player]
        aliases: ['wool']